# fly.toml app configuration file generated for billowing-mountain-928 on 2023-09-18T22:21:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-mountain-928"
primary_region = "syd"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
